name: gs_mesh_debug2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - trimesh==4.0.5
  - SciPy==1.7.3
  - tqdm
  - pip:
    - chumpy==0.70
    - cupy-cuda11x==11.6.0
    - git+https://github.com/szagoruyko/pyinn.git@master
    - pandas==0.25.3
    - matplotlib==3.1.2
    - h5py==2.10.0
    - scikit-learn==0.22.1
    - smplx==0.1.28
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/hypercloud
